import pygame, sys, time

WINDOW_WIDTH = 480
WINDOW_HEIGHT = 800
FRAMERATE = 120

ORIENTATION_TYPES = ['up', 'down']
OBSTACLE_FILENAMES = ['0.png', '1.png']

OBSTACLE_SPEED = 400
BACKGROUND_SPEED = 300