import pygame, sys, time

WINDOW_WIDTH = 480
WINDOW_HEIGHT = 800
FRAMERATE = 120

ORIENTATION_TYPES = ['up', 'down']
OBSTACLE_FILENAMES = ['0.png', '1.png']

BACKGROUND_SPEED = 300
GROUND_SPEED = 360
OBSTACLE_SPEED = 400
GRAVITY_SPEED = 600

JUMP_SIZE = 400
PLANE_ANIMATION_SPEED = 10

N_OF_LIVES = 3